import os
from dotenv import load_dotenv
from src.graph import create_workflow

# load env variable
load_dotenv()

def main():
    print("Starting AI QA automation pipeline... \n")

    # init workflow
    app = create_workflow()

    # define initial state
    initial_state = {
        "target_url": "https://automationteststore.com/",
        "requirements_doc": None,
        "test_cases": [],
        "generated_code": None,
        "test_report": None,
        "retry_count": 0
    }

    # execute the workflow
    print("Executing the graph...\n")
    
    # invoke the graph
    final_state = app.invoke(initial_state)

    # print the results
    print("\nExecution Finished. Final State output:\n")
    print("="*50)
    print("GENERATED PRD (Requirements Document):")
    print("="*50)
    print(final_state.get("requirements_doc"))
    print("="*50)

    print("\n" + "="*50)
    print("GENERATED TEST CASES (BDD Format):")
    print("="*50)
    test_case_list = final_state.get("test_cases")
    if test_case_list:
        print(test_case_list[0])
    print("="*50) 

    # save playwright tests
    generated_code = final_state.get("generated_code")

    # null-check
    if generated_code:
        folder = "generated_tests"

        # create folder if not exist
        if not os.path.exists(folder):
            os.makedirs(folder, exist_ok=True)
        
        # save code to the file
        with open(f"{folder}/test_ui.py", "w", encoding="utf-8") as f:
            f.write(generated_code)

        print("\n" + "="*50)
        print(f"PLAYWRIGHT TESTS HAVE BEEN SAVED in {folder}/test_ui.py")
        print("="*50)

    else:
        print("\n" + "="*50)
        print("No code was generated by the SDET Agent. File not saved.")
        print("="*50)


if __name__ == "__main__":
    main()